/*
 A constants file that contains some coordinates and commmon definitions
 */

#import <Foundation/Foundation.h>
//static const NSString *APIKEY = @"fyc4UOPp9dyIv8JiBkzcN";
@interface Constants : NSObject

#define MAPVIEW_ORIGIN_X 0
#define MAPVIEW_ORIGIN_Y 0 
#define MAPVIEW_SIZE_WIDTH 1024
#define MAPVIEW_SIZE_HEIGHT 748

#define MAP_TOPLEFT_LATITUDE 1.309364 
#define MAP_TOPLEFT_LONGITUDE 103.769703 
#define MAP_TOPLEFT_LATITUDE_LIMIT 1.31935
#define MAP_TOPLEFT_LONGITUDE_LIMIT 103.761372

#define MAP_BOTTOMRIGHT_LATITUDE 1.289392
#define MAP_BOTTOMRIGHT_LONGITUDE 103.786365
#define MAP_BOTTOMRIGHT_LATITUDE_LIMIT 1.279406
#define MAP_BOTTOMRIGHT_LONGITUDE_LIMIT 103.794696


#define PRIVATE_EVENT 0
#define OFFICIAL_EVENT 1

#define IVLE_API_KEY @"fyc4UOPp9dyIv8JiBkzcN"
#define IVLE_LOGIN_URL @"https://ivle.nus.edu.sg/api/Lapi.svc/Validate?APIKey=%@&Token=%@"
#define IVLE_USERNAME_URL  @"https://ivle.nus.edu.sg/api/Lapi.svc/UserName_Get?APIKey=%@&Token=%@"
#define IVLE_USERID_URL @"https://ivle.nus.edu.sg/api/Lapi.svc/UserID_Get?APIKey=%@&Token=%@"
#define IVLE_PULL_EVENTS_URL @"https://aces01.nus.edu.sg/CoE/jsp/coeGenRss.jsp?Cat="
#define IVLE_POST_EVENTS_URL @"https://ivle.nus.edu.sg/api/Lapi.svc/StudentEvents_PostNewEvent"
#define IVLE_POST_EVENTS_DATA @"APIKey=%@&AuthToken=%@&CategoryID=%@&evtdatetimestring=%@&evtdesp=%@&evtPrice=%@&Title=%@&Venue=%@&evtStartDate=%@&evtEndDate=%@"

#define PARSE_APP_ID @"E8GRmmFlMDmYfpfZxDIxyFfCQCaxmJ76MrsTiDwx"
#define PARSE_CLIENT_KEY @"ZV55g4zwiyaskuaUysOPelL2E3nWzdgQhDrd9zH1"


#define IVLE_LOGIN_API_CALL @"https://ivle.nus.edu.sg/api/login/?apikey=fyc4UOPp9dyIv8JiBkzcN&__LASTFOCUS=&__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=%%2fwEPDwULLTEzODMyMDQxNjEPZBYCAgEPZBYEAgEPD2QWAh4Gb25ibHVyBQ91c2VySWRUb1VwcGVyKClkAgkPD2QWBB4Lb25tb3VzZW92ZXIFNWRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdsb2dpbmltZzEnKS5zcmM9b2ZmaW1nLnNyYzE7Hgpvbm1vdXNlb3V0BTRkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbG9naW5pbWcxJykuc3JjPW9uaW1nLnNyYzE7ZBgBBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WAQUJbG9naW5pbWcx&__SCROLLPOSITIONX=0&__SCROLLPOSITIONY=0&userid=%@&password=%@&loginimg1.x=0&loginimg1.y=0"

#define IVLE_LOGIN_API_RESPONSE_LENGTH 416

#define EVENT_DETAIL_VIEW_WIDTH 700
#define EVENT_DETAIL_VIEW_HEIGHT 600
#define CUSTOM_KEYBOARD_WIDTH 1024
#define CUSTOM_KEYBOARD_HEIGHT 310
#define CUSTOM_KEYBOARD_TOOLBAR_WIDTH 320
#define CUSTOM_KEYBOARD_TOOLBAR_HEIGHT 44
#define EVENT_LISTVIEW_BACKGROUND_COLOR_GRAY 200.0/255.0f
#define EVENT_LISTVIEW_BACKGROUND_ALPHA 0.9f
#define EVENT_LISTVIEW_SECTION_ATTEND @"EVENTS TO ATTEND"
#define EVENT_LISTVIEW_SECTION_CREATE @"EVENTS CREATED"
#define EVENT_LISTVIEW_SECTION_ALL @"ALL EVENTS"
#define EVENT_LISTVIEW_HEADER_GRAY1 120.0/255.0f
#define EVENT_LISTVIEW_HEADER_GRAY2 80.0/255.0f
#define EVENT_LISTVIEW_HEADER_LABEL_WIDTH 12.0f
#define EVENT_LISTVIEW_HEADER_LABEL_HEIGHT 5.0f
#define EVENT_LISTVIEW_HEADER_IMAGE_X 250.0f
#define EVENT_LISTVIEW_LIGHTGRAY 215.0/255.0f
#define EVENT_LISTVIEW_CELL_BACKGROUND_GRAY 90.0/255.0f
#define EVENT_LISTVIEW_CELL_TEXT_GRAY 60.0/255.0f
#define EVENT_LISTVIEW_CELL_DETAIL_GRAY 100.0/255.0f

#define SIDEVIEW_SEGMENT_ITEM_0 @"Date"
#define SIDEVIEW_SEGMENT_ITEM_1 @"Week"
#define SIDEVIEW_SEGMENT_ITEM_2 @"All"
#define SIDEVIEW_SEGMENT_X 31.0
#define SIDEVIEW_SEGMENT_Y 10.0
#define SIDEVIEW_SELECTED_BACKGROUND_GRAY 70.0/255.0f
#define SIDEVIEW_SELECTED_TEXT_GRAY 215.0/255.0f
#define SIDEVIEW_CELL_BORDER_GRAY 90.0/255.0f
#define SIDEVIEW_DATEFILTER_TITLE @"DATE FILTERS"
#define SIDEVIEW_TYPEFILTER_TITLE @"TYPE FILTERS"
#define SIDEVIEW_CATEGORYFILTER_TITLE @"CATEGORY FILTERS"
#define SIDEVIEW_WEEKFILTER_ARROW_SIZE 50
#define SIDEVIEW_WEEKFILTER_RIGHTARROW_X 155
#define SIDEVIEW_WEEKFILTER_RIGHTARROW_Y 0
#define SIDEVIEW_WEEKFILTER_LEFTARROW_X 0
#define SIDEVIEW_WEEKFILTER_LEFTARROW_Y 0
#define SIDEVIEW_HEADER_GRAY1 50.0/255.0f
#define SIDEVIEW_HEADER_GRAY2 10.0/255.0f
#define SIDEVIEW_HEADER_LABEL_WIDTH 12.0f
#define SIDEVIEW_HEADER_LABEL_HEIGHT 5.0f
#define SIDEVIEW_HEADER_LABEL_GRAY 215.0/255.0f

typedef enum {kDateFilter, kWeekFilter, kAllFilter} DateFilterType;

typedef enum {kOfficialEvent, kPrivateEvent, kBothEvent} eventCategory;
@end
